import Head from "next/head";
import Image from "next/image";
import { Londrina_Solid } from "next/font/google";
import styles from "@/styles/Home.module.css";
import React, { useEffect, useState } from 'react';
import dynamic from 'next/dynamic';
import { DynamicWidget, useUserWallets } from "@dynamic-labs/sdk-react-core";

const londrina = Londrina_Solid({ subsets: ["latin"], weight: "400" });

const PhaserGameWithNoSSR = dynamic(() => import('../components/PhaserGame'), {
  ssr: false,
});

export default function Home() {
  const [startGame, setStartGame] = useState(false);
  const [address, setAddress] = useState(null);
  const [signer, setSigner] = useState(null);
  const userWallets = useUserWallets();

  const handleStartGame = () => {
    setStartGame(true)
    alert("starting")
  }

  useEffect(() => {
    const getWalletAndSigner = async () => {
      if (userWallets[0]) {
        console.log(userWallets);
        const userWallet = userWallets[0];
        const eoa = userWallet.address;
        console.log({ eoa })
        setAddress(eoa)
        // Delay execution by 2000 milliseconds (2 seconds)
        setTimeout(async () => {
          const signer = await userWallet.connector?.ethers?.getSigner();
          setSigner(signer)
        }, 2000);
      }
    };
    getWalletAndSigner();
  }, [userWallets]);
  
  console.log({ address, signer})
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${londrina.className}`}>
        <Image 
          src="/glasses.png"
          width={205}
          height={200}
          alt="nouns glasses"
        />
        { !address && (
          <div>
            <h1 className={styles.header}>Welcome to Diginouns</h1>
            <p className={styles.subHeader}>Connect and embark on a journey with your noun through an educational RPG meant to teach you the basics of working with Solidity and building smart contracts in a fun engaging way.</p>
          </div>
        )}
        <DynamicWidget />
        {startGame ? (
          <PhaserGameWithNoSSR />
        ) : (
          <div>
          {address && <button className={styles.start} onClick={handleStartGame}>Start Game</button>}
          </div>
        )}
      </main>
      <div className={styles.footerImages}>
        <Image src="/blueface.png" alt="Left Image" width={350} height={350} />
        <Image src="/shroomnount.png" alt="Right Image" width={350} height={350} />
      </div>
    </>
  );
}
